"""Add profile fields

Revision ID: 6d23028f044c
Revises: b913843c4666
Create Date: 2025-03-31 09:43:49.138205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d23028f044c'
down_revision = 'b913843c4666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('current_position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('company')
        batch_op.drop_column('current_position')
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
